name: Deploy MyError App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Laravel dependencies
        # run: composer install

      # - name: Generate Laravel key
      #   run: php artisan key:generate

      - name: Deploy MyError App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/myError/
            rsync -a ./ ./
            php artisan migrate
            php artisan cache:clear
